language: android

sudo: false

jdk: oraclejdk8

notifications:
  email:
    - sebastian.kacprzak@byoutline.com
    - michal.piekarski@byoutline.com

env:
  matrix:
    - ANDROID_TARGET=android-14  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - android-25

licenses:
    - 'android-sdk-license-.+'

script: ./gradlew build  #connectedCheck- espresso test  run on Circle CI