language: android

sudo: false

jdk: openjdk7

notifications:
  email:
    - sebastian.kacprzak@byoutline.com
    - michal.piekarski@byoutline.com

env:
  matrix:
    - ANDROID_TARGET=android-14  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a


#before_script:
#  - echo $JVM_OPTS
#  - unset GRADLE_OPTS JVM_OPTS
#  - export GRADLE_OPTS=-Dorg.gradle.jvmargs="-Xmx1560m -XX:+HeapDumpOnOutOfMemoryError"
#  - export JVM_OPTS=-Xmx512m
#  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window -no-boot-anim &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82

android:
  components:
    - tools
    - android-23
    - platform-tools
    - build-tools-23.0.3
    - extra-android-m2repository

script: ./gradlew build  #connectedCheck- espresso test  run on Circle CI