language: android

jdk: openjdk7

notifications:
  email:
    - sebastian.kacprzak@byoutline.com

env:
  matrix:
    - ANDROID_TARGET=android-14  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-android-m2repository

script: ./gradlew build